# Generated by Django 3.2.5 on 2021-07-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
