# Generated by Django 3.2.5 on 2021-11-19 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IMS', '0003_alter_part_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rma_num', models.CharField(blank=True, max_length=20, null=True)),
                ('serial', models.CharField(blank=True, max_length=25, null=True)),
                ('vendor', models.CharField(blank=True, choices=[('juniper', 'juniper'), ('extreme', 'extreme'), ('accedian', 'accedian'), ('gigamon', 'gigamon'), ('cisco', 'cisco')], max_length=10, null=True)),
                ('part', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.CharField(blank=True, choices=[('WAIT', '출고대기'), ('OUT', '출고')], max_length=5, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
