# Generated by Django 3.2.5 on 2021-11-19 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0004_auto_20211119_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_data', to='IMS.location'),
        ),
        migrations.AlterField(
            model_name='data',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_data', to='IMS.part'),
        ),
        migrations.AlterField(
            model_name='data',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_data', to='IMS.status'),
        ),
        migrations.AlterField(
            model_name='data',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_data', to='IMS.vendor'),
        ),
    ]
